Generalize Dockerfile for multiple package manager

diff --git a/angular/Dockerfile b/angular/Dockerfile
--- a/angular/Dockerfile
+++ b/angular/Dockerfile
@@ -10,10 +10,16 @@ WORKDIR /app
 # Copy only necessary files to install dependencies, this helps in caching layers
 # Use --link to improve performance of caching, recommended in most cases
 # For more information of --link, see https://docs.docker.com/reference/dockerfile/#benefits-of-using---link
-COPY --link package*.json ./
+COPY --link package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 
 # Install dependencies
-RUN npm install
+# Use the appropriate package manager based on the lock file present
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Install Angular CLI globally
 RUN npm install -g @angular/cli@${ANGULAR_VERSION}
@@ -22,9 +28,13 @@ RUN npm install -g @angular/cli@${ANGULAR_VERSION}
 COPY --link . .
 
 # Build the Angular application for production
-# Using the --configuration=production flag to ensure production optimizations
 # This will create a build in the dist/angular/browser directory
-RUN npm run build --configuration=production
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Production stage
 # Use Nginx to serve the built Angular application
